name: Bluefin ISO Build
on:
  workflow_dispatch:

jobs:
  build-40:
    name: Bluefin 40
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 40
