name: Bluefin GTS ISO
on:
  workflow_dispatch:

jobs:
  build-gts:
    name: Bluefin GTS
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 40
